basePath: /api
definitions:
  storage.Song:
    properties:
      group:
        type: string
      link:
        type: string
      releaseDate:
        type: string
      song:
        type: string
      text:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API documentation for your Echo app
  title: Echo API
  version: "1.0"
paths:
  /api/addsong:
    post:
      description: Add song to the database, using group and song name, fetching details
        from other API
      operationId: add-song
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Song and group parameters are required
          schema:
            type: string
        "500":
          description: Failed to add song
          schema:
            type: string
      summary: Add song
  /api/delsong:
    post:
      description: Deletes a song from the database, using song name and group name
        to identify it
      operationId: del-song
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Invalid request body or missing parameters
          schema:
            type: string
        "500":
          description: Failed to delete song
          schema:
            type: string
      summary: Delete song
  /api/editsong:
    post:
      description: Edit song details, using group and song to identify the database
        line, then text, link, releaseDate (of tape Date)
      operationId: edit-song
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Invalid request body or missing parameters
          schema:
            type: string
        "500":
          description: failed to edit song
          schema:
            type: string
      summary: Edit song
  /api/getsong:
    post:
      description: Get song details from the database using group name and song name
      operationId: get-song
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/storage.Song'
            type: array
        "400":
          description: Song and group parameters are required
          schema:
            type: string
        "404":
          description: Song not found
          schema:
            type: string
      summary: Get song
swagger: "2.0"
